### ISSUE TITLE
Proposal: Keygrip v2

### ISSUE THREAD

**Issue by elithrar** [crypto-utils/keygrip#33]
Picking up from https://github.com/pillarjs/cookies/issues/86

**Proposal**:

1. Update the HMAC to HMAC-SHA-256. Rationale: additional future proofing and minimal performance impact (see Notes, below)
2. ~Continue to use the existing `constantTimeCompare` as [`crypto.timingSafeEqual`](https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b) was only introduced into Node v6.6.0 (with 4.x the oldest supported LTS release)~ using `tsscmp` module now
3. Address the critical comments in https://github.com/crypto-utils/keygrip/pull/29 (4, 5, 6 & 7, below)
4. Improve documentation around proper key generation, including an example of using [`crypto.randomBytes`](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) and using keys of the recommended length (16 random bytes -> 32 bytes hex encoded).
5. Consider key stretching with a fixed salt + PBKDF2 to guard against poor keys. This somewhat conflicts against no. 4 (since we want users to provide good keys to begin with), but can go a long way towards protecting users who consume our library indirectly.
6. Remove the ability to choose the algorithm. We should set safe defaults for users.
7. Do NOT add encryption/decryption support (as per #29). Instead, add documentation to direct users to tweetnacl-js's [secretbox](https://github.com/dchest/tweetnacl-js#secret-key-authenticated-encryption-secretbox) functions
8. Confirm the minimum supported Node version, specifically crypto APIs & any past vulnerabilities.
9. Provide a v1 -> v2 migration example.
10. Update tests
11. Help the major importing libraries—namely https://github.com/pillarjs/cookies and https://github.com/koajs/koa (by proxy of cookies)—update to the latest version.

**Notes**:

New API:

```js
var keys = new Keygrip(["7d8d5e535c6ffb7f62fe37e63f199d08", "abb900dff06da35b757dffbd66ef565f"])
var hmac = keys.sign(message)
var index = keys.index(message, expected) // Need to search GitHub to see whether users are correctly checking the return value <= 0 in the wild. This might be a sharp edge.
var valid = keys.verify(message, expected)
```

HMAC performance:
```sh
HMAC-SHA-128 x 300,722 ops/sec ±1.88% (86 runs sampled)
HMAC-SHA-256 x 271,736 ops/sec ±1.84% (80 runs sampled)
HMAC-SHA-512 x 236,938 ops/sec ±2.32% (81 runs sampled)
// I also benchmarked https://github.com/dchest/tweetnacl-auth-js - which provides HMAC-SHA-512/256 - but this was substantially slower and not worth the additional dependencies.
```

constantTimeCompare vs. crypto.safeTimingEqual - no meaningful delta:
```sh
constantTimeCompare x 1,033,767 ops/sec ±1.65% (90 runs sampled)
crypto.timingSafeEqual x 1,106,970 ops/sec ±1.60% (89 runs sampled)
```

Looking forward to feedback.

**Comment by elithrar** [comment]
Ping @dougwilson - when you are OK with (or have feedback relating to) the plan above I can finish off my changes, ideally by end of month.

**Comment by richthegeek** [comment]
@elithrar @blakeembrey @veeti assuming that @dougwilson doesn't have time/inclination to work on this would you guys be interested in working on a fork together?

With regards to the above:

1. Sane defaults are always good, although v1 already supports custom algorithm choices.
2. Unsure of the implications of this - presumably a version check would cause too many problems.
3. +4+5 - #29 seems great as a starting point. Encrypt/decrypt is lovely
6. Personally I don't like removing options. Sane defaults yes. But sometimes hash size is more important than theoretical security.
7. Secretbox doesn't cover the same functionality of Keygrip does it? How would expiring old keys work?
11. Koa/cookies is my use case, so yes.

**Comment by blakeembrey** [comment]
I like the current module API quite a lot and think any changes for a v2 should really be setting up a simpler baseline for consumers to use. If we're making breaking changes, I think only two are necessary:

1. Make `sign` agnostic to the encoding instead of trying to do base64 URL safe encoding for you
2. Add support for a single byte flag to indicate the signing algorithm used 

The single byte flag can be added to the signature for backward compatibility with future releases, or changes to the user signing algorithm (e.g. do for `algorithm` as was done for `keys`). Overall it's a really simple change to support this and would reduce the possible issues in this library. Encryption _could_ be added in a future release, but since it doesn't exist today - is anyone wanting encryption or is just providing a great base for signing keys a good start? In fact, another config compatible library could be written for the encryption/decryption side instead of signing/verifying.

@dougwilson How would you feel about these minimal changes to make `keygrip` easier to consume all around and drop discussions of encryption/decryption for now to minimise the number of issues that can occur.

**Comment by blakeembrey** [comment]
@elithrar @blakeembrey @veeti Took a stab at my preferred API since I use this currently with https://github.com/serviejs/servie-cookie-store and been using a separate encryption library version for at rest data in a side project. Feel free to critique the API of https://github.com/serviejs/keysign and https://github.com/serviejs/keycrypt. Accepts a `Buffer`, returns a `Buffer` and both modules are API compatible with each other so someone could choose signatures or encryption depending on needs (e.g. cookies). The first byte of each is the encryption/signing method for future compatibility and ability to change the algorithm in use.

One thing I realised after pushing it is that these could have been the same module (e.g. `0-127` for signing algorithms, `128-255` for encryption algorithms), but it's probably cleaner for end users to understand encryption is different to signing data.

**Comment by raxell** [comment]
Any update on this? Do you accept PRs for a v2?

**Comment by raxell** [comment]
@dougwilson continuing from https://github.com/expressjs/discussions/issues/59
This is an example of update that I meant. It is not a direct express change but a change to this and other libs would require (assuming node version drop and semver update) a cascading semver update to express. What are your thoughts?

**Comment by dougwilson** [comment]
I'm not sure what that discussion has to do with this module. Not only is this module not a dependency of the `express` module, but it falls completely outside of the Express.js TC and any decision they would make.

**Comment by dougwilson** [comment]
> Do you accept PRs for a v2?

PRs are always accepted to be reviewed. A "v2" PR sounds like something unreviewable, though -- if a PR comes in that completely rewrites a module, then at that point, just publish it as a separate module. If you mean are PRs accepted that is just a single feature or bug fix that may nessisate the bump of semver major component, yes, of course they are.

**Comment by raxell** [comment]
> I'm not sure what that discussion has to do with this module. Not only is this module not a dependency of the `express` module, but it falls completely outside of the Express.js TC and any decision they would make.

I thought that express accepted an instance of keygrip, but it uses another module to sign cookies, my fault, sorry.
