### ISSUE TITLE
keys vulnerability

### ISSUE THREAD

**Issue by AkatQuas** [crypto-utils/keygrip#37]
In the example, after creating `keys`, we can still modify the variable `keylist` out of the instance, which results in variable leak (similar to global variable problem) as well as key rotation in mannual operation.

Is there any way to do key rotation *automatically* and solve the variable leak problem?

**Comment by dougwilson** [comment]
The modification of the `keylist` variable is the feature in which key rotation is performed in this API. The variable's score is controlled by the code you write, and it would only have the score in which you designed your code for. If you don't want it to be a global variable, you don't need to make it a global in your program.

I'm not sure I under stand what you mean by "do key rotation automatically". Can you ellaborate on what this means, specifically? Perhaps an example of automatic key rotation or even a pull request or such?

**Comment by AkatQuas** [comment]
So it means it's the responsibilty for the programmer to do the `keylist` modification, either rotation or even change.

It's a little implicit that the `keylist` is linked to `keys` after the `new` creation.

Would you give me any example/scenario on the why we need to modify the secret keys?

**Comment by dougwilson** [comment]
> It's a little implicit that the keylist is linked to keys after the new creation.

Well, it is in the README documentation, rather than implicit. If you think the docs can be clearer, then let me know what suggestions you have on that point.

> Would you give me any example/scenario on the why we need to modify the secret keys?

So you're using the module to sign data, but you want to cycle in a new key due to the key having a limited lifetime on the service. Rather than restart the entire Node.js process and set up all objects over again, just put the new key as the first element of the array and they everything using the keygrip instance will start signing with the new key.

The general use-cases of key rotation is outside the scope of this module; this module simply provides an API to perform the rotation process itself on the instance.

**Comment by dougwilson** [comment]
Keep in mind that as per the description of this module itself (the first thing in the README) the entire purpose of this module is to allow the modification of the keys for the case where you need to manage key rotation. So if you're asking why you'd want to do that, there is no reason you'd even need to use this module, as you can just use Node.js's `crypto` functions directly with a static key.
